modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/florensie/eggtab/issues"
license = "MIT"

[[mods]]
modId = "eggtab"
version = "${version}"
displayName = "Egg Tab"
authors = "Florens"
description = '''
Moves all spawn eggs and enchanted books to separate creative tabs.
'''
logoFile = "icon.png"

[[dependencies.eggtab]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eggtab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eggtab]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"
