name: Release
on:
  push:
      tags:
        - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build remapSlimJar --stacktrace
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ steps.tag_name.outputs.version }}
      - uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: itsmeow/curseforge-upload@v3
        id: cf_base_release
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 360449
          game_endpoint: minecraft
          file_path: build/libs/eggtab-${{ steps.changelog_reader.outputs.version }}+1.16-fabric.jar
          changelog_type: markdown
          changelog: ${{ steps.changelog_reader.outputs.changes }}
          display_name: ${{ steps.changelog_reader.outputs.version }} for Minecraft 1.16.5-1.18.x
          game_versions: minecraft-1-16:1.16.5,1.17,1.18,1.18.1,1.18.2,fabric
          release_type: release
          relations: fabric-api:requiredDependency,auto-config-updated-api:embeddedLibrary,cloth-config:embeddedLibrary,modmenu:optionalDependency
      - uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 360449
          game_endpoint: minecraft
          parent_file_id: ${{ steps.cf_base_release.outputs.id }}
          file_path: build/libs/eggtab-${{ steps.changelog_reader.outputs.version }}+1.16-fabric-slim.jar
          changelog_type: markdown
          changelog: ${{ steps.changelog_reader.outputs.changes }}
          display_name: ${{ steps.changelog_reader.outputs.version }} (slim) for Minecraft 1.16.5-1.18.x
          game_versions: minecraft-1-16:1.16.5,1.17,1.18,1.18.1,1.18.2,fabric
          release_type: release
          relations: fabric-api:requiredDependency,auto-config-updated-api:requiredDependency,cloth-config:requiredDependency,modmenu:optionalDependency
